---
# Tasks for create hostnames in hosts

- name: Hosts file | Add data about db1
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ db1_ip }} {{ primary_host }}"
    create: yes

- name: Hosts file | Add data about db2
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ db2_ip }} {{ replica_host }}"
    create: yes