---
# tasks file for db-server-mysql

#- name: Mysql | Create hostnames
#  include_tasks: hosts.yml

- name: Mysql | Get install packages
  include_tasks: install.yml

- name: Mysql | Change settings mysql
  include_tasks: settings_mysqld.yml
  
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Mysql replicate | Configure and start replicate
  include_tasks: replicate.yml

- name: Mysql create database | Create database and user for wordpress
  include_tasks: apps.yml
  when: ansible_nodename == "{{ primary_server }}"