---
# Configure Mysql for replication

- name: Mysql configure | Enable remote login to mysql
  become: true
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
  
- name: Mysql configure | server-id for db1
  become: true
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    line: 'server-id = 1'
    create: yes
  when: ansible_nodename == "{{ primary_server }}"
  notify: Restart mysql

- name: Mysql configure | server-id for db2
  become: true
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    line: 'server-id = 2'
    create: yes
  when: ansible_nodename == "{{ replica_server }}"
  notify: Restart mysql